<?php
namespace app\admin\controller;

use app\admin\service\HospitalService;
use think\View;

class Hospital extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function getHospitals()
    {
        $hospitalSer = new HospitalService();
        $res = $hospitalSer->getList(0, 10, true);
        extract($res);
        $this->assign('list', $list);
        $this->assign('page', $page->render());
        return $this->fetch('index');
    }

    public function detail()
    {
        $id = $this->request->get('id');
        $hosSer = new HospitalService();
        $hospital = $hosSer->getHospital($id);
//        var_dump($hospital);die;
        $this->assign('hospital', $hospital);
        return $this->fetch('hospital_detail');
    }

    public function addHospital(){
        $data = $this->request->post();
        if(empty($data)){
            return $this->fetch('add');
        }
        $hosSer = new HospitalService();
        $id = $hosSer->add($data);
        if(empty($id)){
            return $this->success('新增失败','/examination/public/');
        }
        return $this->success('新增成功','/examination/public/');
    }



}
