<?php
namespace app\admin\controller;

use app\index\service\HospitalService;
use app\index\service\PackageService;
use think\View;

class Index extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
//        $hospitalSer = new HospitalService();
//        $packSer = new PackageService();
//        $hospitalList = $hospitalSer->getList(0,6);
//        $packList = $packSer->getList(0,6);
//        $this->assign('hospitals',$hospitalList);
//        $this->assign('packages',$packList);
        return $this->fetch();
    }
}
