<?php
namespace app\admin\controller;

use app\index\service\HospitalService;
use app\index\service\PackageService;
use think\View;

class Index extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $user = $this->getUserInfo();
        $this->assign('user',$user);
        return $this->fetch();
    }
}
