<?php
namespace app\admin\controller;

use app\admin\service\PackageService;
use think\View;

class Package extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function getPackages()
    {
        $packSer = new PackageService();
        $res = $packSer->getPaginateList(10);
        extract($res);
        $this->assign('list',$list);
        $this->assign('page',$page->render());
        return $this->fetch('index');
    }

    public function getPackage()
    {
        $id = $this->request->get('id');
        $packSer = new PackageService();
        $package = $packSer->getPackage($id);
//        var_dump($package);die;
        $this->assign('package',$package);
        return $this->fetch('package_detail');
    }

    public function editPackage()
    {
        $data = $this->request->post();
        $packSer = new PackageService();
        if(empty($data)){
            $id = $this->request->get('id');
            if(empty($id)) return $this->error('出错了！！',ADMIN_URL_PATH);
            $package = $packSer->getPackage($id);
            $this->assign('package',$package);
            return $this->fetch('detail');

        }
        $package = $packSer->updatePackage($data);
        return $this->success('更新成功',ADMIN_URL_PATH.'packageList');
    }
}
