<?php
namespace app\admin\controller;

use app\admin\service\ProjectCategoryService;
use app\admin\service\ProjectService;


class Project extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function getProjects()
    {
        $proSer = new ProjectService();
        $res = $proSer->getPaginateList(10);
        return $this->fetch('index',$res);
    }

    public function getProject()
    {
        $id = $this->request->get('id');
        $proSer = new ProjectService();
        $project = $proSer->getProject($id);
        $this->assign('project',$project);
        return $this->fetch('project_detail');
    }

    public function editProject()
    {
        $data = $this->request->post();
        $proSer = new ProjectService();
        if(empty($data)){
            $id = $this->request->get('id');
            if(empty($id)) return $this->error('出错了！！',ADMIN_URL_PATH);
            $project = $proSer->getProject($id);
            $cateSer = new ProjectCategoryService();
            $cateList = $cateSer->getList();
            $this->assign('project',$project);
            $this->assign('category',$cateList);
            return $this->fetch('detail');
        }
//        var_dump($data);die;
        $project = $proSer->updateProject($data);
        return $this->success('更新成功',ADMIN_URL_PATH.'projectList');
    }

    public function addProject()
    {
        $data = $this->request->post();
        $proSer = new ProjectService();
        if(empty($data)){
            $cateSer = new ProjectCategoryService();
            $cateList = $cateSer->getList();
            $this->assign('category',$cateList);
            return $this->fetch('add');
        }
//        var_dump($data);die;
        $id = $proSer->addProject($data);
        if(empty($id)){
            return $this->error('新增失败',ADMIN_URL_PATH.'projectAdd');
        }
        return $this->success('新增成功',ADMIN_URL_PATH.'projectEdit?id='.$id);
    }
}
